{% set version = "4.8.7" %}

package:
  name: qt
  version: {{ version }}

source:
  fn: qt-everywhere-opensource-src-{{ version }}.tar.gz
  url: https://download.qt.io/archive/qt/4.8/{{ version }}/qt-everywhere-opensource-src-{{ version }}.tar.gz
  sha256: e2882295097e47fe089f8ac741a95fef47e0a73a3f3cdf21b56990638f626ea0
  patches:
    - config.cpp.longpath.patch  # [win]
    # Make Qt accept its open source license without user interaction
    - acceptance.patch
    # Make the paths in config.cpp longer so they work with conda-build 2.x
    - config.cpp.longpath.patch  # [unix]
    # Compile qmake with the system architecture. Taken from the MacPorts project:
    # https://trac.macports.org/browser/trunk/dports/aqua/qt4-mac/files/patch-configure.diff
    - qmake-arch.patch  # [osx]
    # Set the minimum deployment target to 10.9
    - osx_deployment_target_10.9_qmake.conf.patch  # [osx]
    # Enabling our test to set the rpath by making Qt aware
    # of how to do this on OSX
    - osx_rpath.qmake.conf.patch  # [osx]
    # Set osx C++11 config
    - osx_set_c98_cgf.patch  # [osx]
    # fix use of deprecated OSX API. Taken from Homebrew:
    # https://github.com/Homebrew/legacy-homebrew/issues/40585
    - qpaintengine_mac.patch  # [osx]
    # Make Qt work with Ubuntu modifications to scrollbars for Gtk
    - ubuntu_disable_scrollbars.patch  # [linux]
    # Build QtWebkit with gcc-6, on platform linux-g++
    - qtwebkit-gcc-6.patch  # [linux]
    # Disable warning about Windows 10 not being a supported platform by Qt
    - disable_win10_warning.patch  # [win]
    # On Windows, for VS 2015 (Python 3.5+), rather drastic modifications are
    # necessary because Microsoft finally got around to defining some standard
    # functions. There's the vs_2015_int.patch file that does this. The changes in this patch were
    # found in forums, and originated at (Author appears to be Peter Zhigalov):
    # https://fami.codefreak.ru/gitlab/peter/qt4/commit/45e8f4eef3923e03c6939d0c17170980685857ef.diff
    - vs2015_int_fix.patch  # [win and py >= 35]
    # see https://bugreports.qt.io/browse/QTBUG-37209
    # fix phonon exports so they can be linked to
    - phonon_osx_exports.patch  # [osx]
    # - moc_fix_includes.patch  # [win]

build:
  number: 1000
  # skipping linux for now, because it is already being packaged on Linux
  # Just to save some time in our CIs
  skip: true  # [linux or win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - perl
    - python  2.7  # [unix]
    - xz

  host:
    - freetype 2.7|2.7.*  # [unix]
    - fontconfig 2.12.*  # [linux]
    - freeglut  # [linux]
    - openssl 1.0.*
    - jpeg 9*
    - libtiff 4.0.*
    - zlib 1.2.*
    - libpng >=1.6.28,<1.7
    - jom  # [win]
    - icu 58.*
    - xorg-libice      # [linux]
    - xorg-libsm       # [linux]
    - xorg-libx11      # [linux]
    - xorg-libxext     # [linux]
    - xorg-libxrender  # [linux]
    - xorg-libxt       # [linux]
    - xorg-inputproto  # [linux]
    - expat  # [unix]
    - sqlite

  run:
    - freetype 2.7|2.7.*  # [unix]
    - fontconfig 2.12.*  # [linux]
    - pango  # [linux]
    - openssl 1.0.*
    - libpng >=1.6.28,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - zlib 1.2.*
    - icu 58.*
    - xorg-libice      # [linux]
    - xorg-libsm       # [linux]
    - xorg-libx11      # [linux]
    - xorg-libxext     # [linux]
    - xorg-libxrender  # [linux]
    - xorg-libxt       # [linux]
    - sqlite

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    
  files:
    - test
  commands:
  
    - conda inspect linkages -p $PREFIX qt  # [not win]
    - conda inspect objects -p $PREFIX qt  # [osx]

about:
  home: http://qt-project.org
  license: LGPL
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qtproject

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - gillins
    - msarahan
    - marcelotrevisani
